### ISSUE TITLE
namespace 能不能大写啊？

### ISSUE THREAD

**Issue by lucups** [bixuehujin/skyray#2]
强烈建议 namespace 使用大写。
我可以帮你改。：）
这种苦力活比较适合我~

**Comment by bixuehujin** [comment]
I would prefer the Yii namespace style, which is more  clean :)

**Comment by lucups** [comment]
I will fork the project and make a new branch to do it :)

**Comment by bixuehujin** [comment]
Do what? capital namespaces? no, no, no ...   I'd more like the Yii style of short and clean namespaces.
